name: .NET Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x' # Set this to the specific version or use '7.0.x' for latest patch

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -f net7.0 --no-build -o ./publish

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: ./publish
